### ISSUE TITLE
No Checklist Button on Editor

### ISSUE THREAD

**Issue by cavargus** [checklist/wordpress#2]
Hi there,

I installed the plugin via adding a new plugin in WP and searching for your plugin.  The plugin is installed and activated.

The problem I have run into is that there is no checklist button on the standard editor.

https://gyazo.com/b41617dab8c976c0832aa62b0f8fe1d4

**Comment by sunburntexplorer** [comment]
If you download the plugin WP classic editor you can switch to the older setting which allows this plugin to work. You can then go into the classic editor settings to 'allow users to switch editors' so you can use which editor you want when you want. When you publish or preview the checklist it will look like it is supposed to.

**Comment by checklist** [comment]
@sunburntexplorer - thanks. That is true. Simply working with Classic should fix the issue.
